### ISSUE TITLE
MetaSpotify::Track.search("a") gives undefined method `to_params' for {:q=>"a"}:Hash

### ISSUE THREAD

**Issue by MPV** [philnash/meta-spotify#2]
Hi, 
I just upgraded my Rails 3.0.0 app to Rails 3.1.0 and I started getting a problem with the meta-spotify gem:

When running:

```
MetaSpotify::Track.search("coldplay")
```

I get:

```
undefined method `to_params' for {:q=>"coldplay"}:Hash
```

Do you have any idea why this happens?

I didn't change the Ruby version, I'm using Ruby 1.9.2 both before and after the Rails upgrade. 

If a code sample helps, this is how my code looks like:

https://github.com/BigNetwork/BIP/blob/bootstrap-rails-upgrade/app/controllers/search_controller.rb#L26

**Comment by philnash** [comment]
Hey,

This appears to be due to a mismatch between the versions of HTTParty and Crack that your app has installed. You have HTTParty 0.5.0, which requires Crack >=0.1.1, but in reality it also requires it to be <0.3.0 which is where the to_params Hash extension was removed.

To fix this in your app, you'll need to update HTTParty (to anything up to 0.7.8) or downgrade Crack (to 0.2.0).

I think I need to update this gem and possibly remove the dependency on HTTParty which has been getting flaky (for me) more recently.

Let me know if this helps!

Phil

**Comment by philnash** [comment]
Updated gem to use httparty > 0.8. With version 0.2.0 this will not be an issue.
